baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Material Design"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
#enableGitInfo = true
publishDir = "docs"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.drawer]]
    name = "Home"
    url = "/"
    pre = "<i class='fa fa-home'></i>"
    weight = 1
[[menu.drawer]]
    name = "Test"
    url = "/test"
    pre = "<i class='fa fa-user'></i>"
    weight = 2
[[menu.drawer]]
    name = "Signup"
    url = "/signup"
    weight = 3

[[menu.top]]
    identifier = "twitter"
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://twitter.com/CreativeTim"
    weight = 4
[[menu.top]]
    identifier = "github"
    pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/CreativeTim"
    weight = 4

[[menu.footer]]
  weight = 1
  identifier = "Berkeley"
  name = "UC Berkeley"
  pre = "<i class=\"material-icons\">pin_drop</i>"
  url = "https://data.berkeley.edu"
[[menu.footer]]
  weight = 2
  identifier = "GitHub"
  name = "Team Repos"
  pre = "<i class=\"button-icon fa fa-2x fa-github\"></i>"
  url = "https://github.com/espm-157"
[[menu.footer]]
  weight = 3
  identifier = "Piazza"
  name = "Forum"
  pre = "<i class=\"material-icons\">forum</i>"
  url = "https://piazza.com/berkeley/fall2017/espm157/home"

[params]
    background = "/img/nasa_melting.jpg"
#    background = "/img/noaa-ice-large-cc0.jpg"
#    background = "https://climate.nasa.gov/system/internal_resources/details/original/417_1263_banner-science-1600x500.jpg"
    custom_css = ["creative-tim.css"]
#    custom_js = ["example.js"]
    
    date_format = "Mon, Jan 2, 2006"
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

    

